config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships
  resources :posts
  resources :likes
  resources :hates
  root 'pages#index'
  
  delete 'user' => 'users#delete'
  
  delete 'ban'  => 'users#ban_user'
  
  post 'login' => 'session#create'

  post 'logout' => 'session#destroy'
  
  post 'change_password' => 'users#change_password'
  
  post 'change_avatar' => 'users#change_avatar'
  
  post 'like' => 'likes#create'
  
  post 'hate' => 'hates#create'
  
  post '/subhoot' => 'subhoots#create'
  
  post '/hoot' => 'posts#hoot'
  
  get '/my_timeline' => 'posts#timeline'
  
  get '/my_timeline_update/:id' => 'posts#timeline_update'
  
  get '/all_hoots' => 'posts#explore'
  
  get '/all_hoots_update/:id' => 'posts#explore_update'
  
  get '/hoots_for/:id' => 'posts#hoots_for'
  
  get '/memes' => 'posts#memes'
  
  get '/fellow_hooters' => 'users#fellow_hooters'
  
  get '/hoot_hoots' => 'posts#hoot_hoots'
  
  get '/hoot_hoots_update/:id' => 'posts#hoot_hoots_update'
  
  get '/followings_for/:id' => 'relationships#followings_for'
  
  get '/followers_for/:id' => 'relationships#followers_for'
  
  get '/hoots_through_regex/:search' => 'posts#hoots_through_regex'
  
  get '/hooters_through_regex/:search' => 'users#hooters_through_regex'
  
  get '/single_json/:id' => 'posts#single_json'
  
  get '/get_subhoots/:id' => 'subhoots#get_subhoots'
  
  get '/get_subhoots_update/:id/:from_id' => 'subhoots#get_subhoots_update'
  
  get '/search' => 'pages#search'

  get '/edit_profile' => 'pages#edit_profile'

  get '/login' => 'pages#login'
  
  get '/signup' => 'pages#signup'
  
  get '/home' => 'pages#home'
  
  get '/help' => 'pages#help'
  
  get '/one_hoot' => 'pages#one_hoot'

  get '/explore' => 'pages#explore'
  
  get '/hoots' => 'pages#hoots'
  
  get '/following/:id' => 'pages#following'
  
  get '/followers/:id' => 'pages#followers'
  
  get '/single_hoot' => 'pages#no_hoot'
  
  get '/single_hoot/:id' => 'pages#single_hoot'
  
  get '/:id' => 'pages#profile'

end

app/views/pages/edit_profile.html.erb
<div class = 'row'>
    <div class = "col-xs-3 col-xs-offset-3">
        <%= form_for(:user, url: change_password_path) do |f| %>
            <div><%= f.label :change_password? %></div>
            <div><%= f.password_field :password, :placeholder => "current passord" , :class => "form-control" %></div>
            <div><%= f.password_field :new_password, :placeholder => "new password", :class => "form-control" %></div>
            <div><%= f.password_field :new_password_confirm, :placeholder => "new password confirm", :class => "form-control" %></div>
            <div><%= f.submit "Change Password", class: "btn btn-warning" %></div>
        <% end %>
    </div>
    <div class = "col-xs-3">
        <%= form_for(:user, url: change_avatar_path) do |f| %>
            <div><%= f.label :change_profile_picture? %></div>
            <div><%= f.password_field :password, :placeholder => "current passord", :class => "form-control" %></div>
            <div><%= f.text_field :avatar, :placeholder => "new avatar url", :class => "form-control" %></div>
            <div><%= f.submit "Change Avatar", class: "btn btn-warning" %></div>
        <% end %>
    </div>
</div>
<%= render 'components/kill_button' %>

app/views/pages/explore.html.erb
<div class = "row" >
    <div class = "col-xs-6 col-xs-offset-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p class="title-text"> hoots around the world </p>
            </div>
         </div>
        <div id = timeline>
            </div>
            <script>
                $(document).ready(render_explore);
            </script>
            <div class="panel panel-default end-panel">
            <div class="panel-body">
                <center> END </center>
            </div>
         </div>
    </div>
    <div class = "col-xs-3">
        <div class="panel panel-default">
             <div class="panel-body">
                <%= render '/components/meme_box' %>
            </div>
       </div>
       <div class="panel panel-default">
            <div class="panel-body">
               <%= render '/components/peeps_box' %>
            </div>
        </div>
    </div>
</div>

app/views/pages/followers.html.erb
<% if !(User.find_by_name(@username)) %>


    <%= render '/components/no_user_found' %>

<% else %>

    <div class = "row" >
        <div class = "col-xs-6 col-xs-offset-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p class = "title-text"> followers of  <%=@username%></p>
                </div>
             </div>
            <div id='followers-box' class="panel panel-default">
            </div>
            <script>
            $(document).ready(function(){
            render_followers("<%=@username%>");
            });
            </script>
        </div>
        <div class = "col-xs-3">
            <div class="panel panel-default">
                 <div class="panel-body">
                    <%= render '/components/meme_box' %>
                </div>
           </div>
           <div class="panel panel-default">
                <div class="panel-body">
                   <%= render '/components/peeps_box' %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/pages/following.html.erb
<% if !(User.find_by_name(@username)) %>
    <%= render '/components/no_user_found' %>
<% else %>

        <div class = "row" >
            <div class = "col-xs-6 col-xs-offset-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p class = "title-text"> <%=@username%> is following </p>
                    </div>
                 </div>
                <div id='following-box' class="panel panel-default">
                </div>
                <script>
            $(document).ready(function(){
            render_following("<%=@username%>");
            });
            </script>
            </div>
            <div class = "col-xs-3">
                <div class="panel panel-default">
                     <div class="panel-body">
                        <%= render '/components/meme_box' %>
                    </div>
               </div>
               <div class="panel panel-default">
                    <div class="panel-body">
                       <%= render '/components/peeps_box' %>
                    </div>
                </div>
            </div>
        </div>
        
<% end %>

app/views/pages/help.html.erb
<div class = "col-xs-6 col-xs-offset-3">
    <p style = 'font-size: 900%'> FAQ </p>
    <p>no one has asked me anything yet.......</p>
    <p> contact me at <a href = mailto:codyjamesmcmahon@gmail.com?Subject=help>codyjamesmcmahon@gmail.com<a> </p>
</div>

app/views/pages/home.html.erb
<% if !user_signed_in? %>
    <script> document.location = '/' </script>
<% else %>
    <div class = "row" >
        <div class = "col-xs-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= render '/components/profile_box' %>
                </div>
             </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= render '/components/meme_box' %>
                </div>
             </div>
        </div>
        <div class = "col-xs-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p> <%= render '/components/hoot_form' %></p>
                </div>
             </div>
             <div id = timeline>
            </div>
            <script>
                $(document).ready(render_time_line);
            </script>
            <div class="panel panel-default end-panel">
            <div class="panel-body">
                <center> END </center>
            </div>
         </div>
        </div>
        <div class = "col-xs-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href = "mailto:codyjamesmcmahon@gmail.com?Subject=WOW!!%20YOU%20ARE%20THE%20GREATEST!!!!!!"> please hire me </a>
                </div>
             </div>
             <div class="panel panel-default">
                <div class="panel-body">
                   <%= render '/components/peeps_box' %>
                </div>
            </div>
        </div>
    </div>
<% end %>
<!--meme comment xdddddddddddddd -->

app/views/pages/hoots.html.erb
<div class = "row" >
    <div class = "col-xs-6 col-xs-offset-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p class="title-text"> where da hoots @ </p>
            </div>
         </div>
        <div id = timeline>
            </div>
            <script>
                $(document).ready(render_hoot_hoots);
            </script>
            <div class="panel panel-default end-panel">
            <div class="panel-body">
                <center> END </center>
            </div>
         </div>
    </div>
    <div class = "col-xs-3">
       <div class="panel panel-default">
            <div class="panel-body">
               <%= render '/components/peeps_box' %>
            </div>
        </div>
        <div class="panel panel-default">
             <div class="panel-body">
                <%= render '/components/meme_box' %>
            </div>
       </div>
    </div>
</div>

app/views/pages/index.html.erb
<% if !user_signed_in? %>
    <%= render '/components/landing' %>
<% else %>
    <script>document.location = '/home'</script>
<% end %>

app/views/pages/login.html.erb
<div class = "col-xs-6 col-xs-offset-3">
<h2>Log in and start hooting</h2>

<%= form_for(:session, url: login_path) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :placeholder => "name", autofocus: true , class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :placeholder => "password", autocomplete: "off" , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit "Log in" , class: 'btn btn-default'%>
  </div>
<% end %>
<a href='/signup'><p>new hooter?</p></a>
<!--<a href='/users/password/new'><p>bad memory?(forgotten password)</p></a>-->
</div>

app/views/pages/no_hoot.html.erb
<p> NO HOOT SPECIFIED :((( </p>

app/views/pages/profile.html.erb
<% if !(User.find_by_name(params[:id])) %>
    <%= render '/components/no_user_found' %>
<% else %>


    <div class = "row" >
        <div class = "col-xs-12">
            <div class="jumbotron">
                <h1>give ya boi <%= @username %> a hoot hoot!</h1>
            </div>
        </div>
    </div>  

    <div class = "row" >
        <div class = "col-xs-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= render '/components/profile_box' %>
                </div>
            </div>
            <% if user_signed_in? %>
                <% if @this_user.id != current_user_id %>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <%= render '/components/follow_button' %>
                            <% if current_user.is_admin? %>
                                <%= render '/components/ban_button' %>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <div class = "col-xs-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p class="title-text"> <%= @username %>'s hoots </p>
                </div>
             </div>
             
            <div id = timeline>
                </div>
                <script>
                    render_hoots_for("<%= @username %>");
                </script>
                <div class="panel panel-default end-panel">
                <div class="panel-body">
                    <center> END </center>
                </div>
             </div>
       </div>
        <div class = "col-xs-3">
            <div class="panel panel-default">
                <div class="panel-body">
                   <%= render '/components/peeps_box' %>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= render '/components/meme_box' %>
                 </div>
            </div>
        </div>
    </div>
<% end %>
<!--meme comment xdddddddddddddd -->

app/views/pages/search.html.erb
<div class = "row" >
    <div class = "col-xs-6 col-xs">
        <div class="panel panel-default">
            <div class="panel-body">
                <p class='title-text'>hooters found</p>
            </div>
         </div>
        <div id="hooters-holding-object" class="panel panel-default">
        </div>
        <script>render_hooters_through_regex("<%= params[:search] %>");</script>
    </div>
    <div class = "col-xs-6 col-xs">
        <div class="panel panel-default">
            <div class="panel-body">
                <p class='title-text'>posts found</p>
            </div>
         </div>
         <div id='timeline'>
         </div>
        <script>render_hoots_through_regex("<%= params[:search] %>");</script>
        <div class="panel panel-default end-panel">
            <div class="panel-body">
                <center> END </center>
            </div>
         </div>
    </div>
</div>

app/views/pages/signup.html.erb
<div class = "col-xs-6 col-xs-offset-3">
  <h2>Sign up and start hooting friend :)</h2>
  
  <%= form_for(@user) do |f| %>
  
    <div class="field">
      <%= f.label "name (max size 20) (numbers letters underscores and spaces are allowed)" %><br />
      <%= f.text_field :name, :placeholder => "you are name here", autofocus: true , class: 'form-control'%>
    </div>
      <div class="field">
          <%= f.label 'Profile_Image_(optional)' %><br />
          <%= f.text_field :profile_image, :placeholder => "image url (optional)", :value => '', class: 'form-control'%>
        </div>
  
    <div class="field">
      <%= f.label "password (min size 2)" %>
      <%= f.password_field :password, :placeholder => "password", autocomplete: "off" , class: 'form-control'%>
    </div>
  
    <div class="field">
      <%= f.label "Password Confirmation" %><br />
      <%= f.password_field :password_confirmation, :placeholder => "confirm password", autocomplete: "off" , class: 'form-control'%>
    </div>
  
    <div class="actions">
      <%= f.submit "Sign up" , class: 'btn btn-default'%>
    </div>
  <% end %>
  
  <a href = '/login'>already have an account?</a>
</div>

app/views/pages/single_hoot.html.erb
<% if @hoot %>
    <% @p = @hoot %>
    <div class = "col-xs-6 col-xs-offset-3">
        <div id='timeline'></div>
        <script>
        render_single_hoot("<%= params[:id] %>");
        </script>
        <div id="subhoot-timeline-<%= params[:id] %>"></div>
        <script>
        render_subhoot_timeline("<%= params[:id] %>");
        </script>
        <% if user_signed_in? %>
            <%= render '/components/subhoot_form' %>
        <% end %>
    </div>
<% else %>
    <p> no hoot found </p>
<% end %>